name: Infrastructure as Code - Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "infrastructure/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}

      - name: Debug env
        run: |
          echo "github.event.repository.name: ${{ github.event.repository.name }}"
          echo "github.event.repository.owner: ${{ github.event.repository.owner }}"
          echo "github.event.repository.owner.name: ${{ github.event.repository.owner.name }}"
          echo "github.event.repository: ${{ github.event.repository }}"

      - name: Create tofu plan for core
        id: plan
        uses: dflook/tofu-plan@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        with:
          path: ./infrastructure/core
          label: Core
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state
          variables: |
            gh_pat_token = "${{ secrets.GH_PAT_TOKEN }}"
            gh_owner = "${{ github.event.repository.owner.name }}"
            gh_repo_name = "${{ github.event.repository.name }}"
