name: Tofu - Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "infrastructure/**"

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
  SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
  SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}

jobs:
  fmt-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check formatting
        uses: dflook/tofu-fmt-check@v2
        with:
          path: ./infrastructure

  core:
    name: Plan core changes
    needs: fmt-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tofu plan for core
        uses: dflook/tofu-plan@v2.1.0
        with:
          path: ./infrastructure/core
          label: Core
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state
          variables: |
            gh_pat_token = "${{ secrets.GH_PAT_TOKEN }}"
            gh_repo_name = "${{ github.event.repository.name }}"

  environments:
    needs: core
    name: Plan environments changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - dev
          - staging
          - prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tofu plan for ${{ matrix.environment }}
        uses: dflook/tofu-plan@v2.1.0
        with:
          path: ./infrastructure/envs/${{ matrix.environment }}
          label: ${{ matrix.environment }}
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state
          variables: |
            gh_pat_token = "${{ secrets.GH_PAT_TOKEN }}"
            gh_repo_name = "${{ github.event.repository.name }}"
