name: Tofu - Apply

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  core:
    name: Apply core changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          app-id: ${{ vars.TOFU_MANAGER_CLIENT_ID }}
          private-key: ${{ secrets.TOFU_MANAGER_APP_SECRET }}

      - name: Apply core changes
        uses: dflook/tofu-apply@v2.1.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        with:
          path: ./infrastructure/core
          label: Core
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state
          variables: |
            gh_repo_name = "${{ github.event.repository.name }}"

  environments:
    needs: core
    name: Apply environments changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - dev
          - staging
          - prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          app-id: ${{ vars.TOFU_MANAGER_CLIENT_ID }}
          private-key: ${{ secrets.TOFU_MANAGER_APP_SECRET }}

      - name: Apply ${{ matrix.environment }} changes
        uses: dflook/tofu-apply@v2.1.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
        with:
          path: ./infrastructure/envs/${{ matrix.environment }}
          label: ${{ matrix.environment }}
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state
          variables: |
            gh_repo_name = "${{ github.event.repository.name }}"
            scw_access_key = "${{ secrets.SCW_ACCESS_KEY }}"
            scw_secret_key = "${{ secrets.SCW_SECRET_KEY }}"
            scw_organization_id = "${{ secrets.SCW_ORGANIZATION_ID }}"
