name: Preview - Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, closed]
    branches: [main]

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

jobs:
  check-labels:
    runs-on: ubuntu-latest
    outputs:
      should-apply: ${{ steps.check.outputs.should-apply }}
      should-destroy: ${{ steps.check.outputs.should-destroy }}
      should-deploy: ${{ steps.check.outputs.should-deploy }}
    steps:
      - name: Determine actions
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('../../.github/scripts/preview-determine-actions.js');
            await scripts({ github, context, core });
      - name: Debug
        run: |
          echo "should-deploy: ${{ steps.check.outputs.should-deploy }}"
          echo "should-apply: ${{ steps.check.outputs.should-apply }}"
          echo "should-destroy: ${{ steps.check.outputs.should-destroy }}"
