name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, closed]
    branches: [main]

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.12.2
          run_install: false

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: pnpm sherif

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: pnpm exec nx affected -t lint test build

  determine-actions:
    needs: lint-test-build
    name: Determine actions
    runs-on: ubuntu-latest
    outputs:
      should-destroy: ${{ steps.check.outputs.should-destroy }}
      should-deploy: ${{ steps.check.outputs.should-deploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine actions
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('./.github/scripts/preview-determine-actions.js');
            await scripts({ github, context, core });

  deploy:
    name: Deploy preview
    runs-on: ubuntu-latest
    needs: determine-actions
    if: fromJSON(needs.determine-actions.outputs.should-deploy)
    environment: pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Report state (deploying)
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('./.github/scripts/report-state.js');
            await scripts({ github, context, core }, {
              deploy: 'deploying'
            });

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          app-id: ${{ vars.TOFU_MANAGER_CLIENT_ID }}
          private-key: ${{ secrets.TOFU_MANAGER_APP_SECRET }}

      - name: Create tofu workspace
        uses: dflook/tofu-new-workspace@v2.1.0
        with:
          path: ./infrastructure/envs/preview
          workspace: pr-${{ github.event.pull_request.number }}
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state

      - name: Apply Tofu plan
        uses: dflook/tofu-apply@v2.1.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        with:
          path: ./infrastructure/envs/preview
          label: preview
          auto_approve: true
          workspace: pr-${{ github.event.pull_request.number }}
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state
          variables: |
            gh_repo_name = "${{ github.event.repository.name }}"
            pr_number = "${{ github.event.pull_request.number }}"

      - name: Deploy application
        run: |
          echo "Deploying application"

      - name: Report state (deployed)
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('./.github/scripts/report-state.js');
            await scripts({ github, context, core }, {
              deploy: 'deployed'
            });

      - name: Report state (failure)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('./.github/scripts/report-state.js');
            await scripts({ github, context, core }, {
              deploy: 'failure'
            });

  cleanup:
    name: Clean up preview
    runs-on: ubuntu-latest
    needs: determine-actions
    if: fromJSON(needs.determine-actions.outputs.should-destroy)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Report state (destroying)
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('./.github/scripts/report-state.js');
            await scripts({ github, context, core }, {
              deploy: 'destroying'
            });

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          app-id: ${{ vars.TOFU_MANAGER_CLIENT_ID }}
          private-key: ${{ secrets.TOFU_MANAGER_APP_SECRET }}

      - name: Destroy Tofu plan
        uses: dflook/tofu-destroy-workspace@v2.1.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        with:
          path: ./infrastructure/envs/preview
          workspace: pr-${{ github.event.pull_request.number }}
          backend_config: |
            access_key=${{ secrets.SCW_ACCESS_KEY }}
            secret_key=${{ secrets.SCW_SECRET_KEY }}
            bucket=${{ github.event.repository.name }}-tofu-state
          variables: |
            gh_repo_name = "${{ github.event.repository.name }}"
            pr_number = "${{ github.event.pull_request.number }}"

      - name: Report state (destroyed)
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('./.github/scripts/report-state.js');
            await scripts({ github, context, core }, {
              deploy: 'destroyed'
            });

      - name: Report state (failure)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const scripts = require('./.github/scripts/report-state.js');
            await scripts({ github, context, core }, {
              deploy: 'failure'
            });
